### ISSUE TITLE
Error: Cannot find module 'node_modules/matrix-js-sdk/lib/index.js'. Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by devsnek** [matrix-org/matrix-js-sdk#1168]
Version: 4.0.0-rc.1 (tagged latest in npm registry)
I'm using Node.js 13.7.0.

the package.json specifies that `./lib/index.js` should be used as the entry-point, but no such file exists. `lib/matrix.js` exists, and appears to have the exports that should be used, but when i require it `require('matrix-js-sdk/lib/matrix')`, it tries to require `@babel/runtime/helpers/interopRequireDefault`, which is not a dependency of `matrix-js-sdk` and is not installed.

**Comment by jryans** [comment]
Sorry about this! 😓 As part of the 4.x release, we've reworked our build process, so that's likely how something went wrong here. I'll raise this with the team tomorrow. Thanks for filing!

**Comment by jryans** [comment]
Rather than waiting for a fix, the 3.x series should be working fine, so that's another option as well.

**Comment by devsnek** [comment]
@jryans 3.x has the right files at least, but it still throws that babel error.

**Comment by turt2live** [comment]
I don't know why the index isn't there, but it looks like the RC we cut is older than the release branch so it could be a build problem. Running the steps myself gives me the right files.

As for babel runtime: oops.

**Comment by salzig** [comment]
Why is this closed? This one bite me today. 
```
  "name": "matrix-js-sdk",
  "version": "4.0.0-rc.1",
```
on npmjs.org is still broken! Could you update npmjs.org when you did fix the package build?

**Comment by turt2live** [comment]
We always close issues when they're fixed on develop, not when they're released. Assuming everything goes according to plan, this should be fixed tomorrow on npm.

**Comment by salzig** [comment]
Sorry, my last message sounds not very nice. Tried for quite a while to get it working, and expected an error on my side as the version described mentioned "release candidate". I didn't expected such a "minor" problem. In the end i wasted a lot of hours and it would have helped when the version had been marked as beta (then i had not used it) or a new RC had been published after to problem got fixed.

**Comment by jryans** [comment]
4.0.0 has now been published to npm, which should contain the fix here. If that's still broken, please do let us know.

**Comment by turt2live** [comment]
(we also filed https://github.com/vector-im/riot-web/issues/12029 to prevent the RC from going into the live channel in the future)

**Comment by salzig** [comment]
4.0.0 works fine so far (connecting to server and listing public rooms).

Thanks!
