### ISSUE TITLE
Missing olm module

### ISSUE THREAD

**Issue by mudcrab** [matrix-org/matrix-js-sdk#301]
Hello!

When trying to include browser-matrix.js (either from realease or building yourself), you get an error stating olm module loading error

```
olm load error Error: Cannot find module 'olm'
    at s (matrix.js:1)
    at matrix.js:1
    at Object.5.../utils (matrix.js:4412)
    at s (matrix.js:1)
    at matrix.js:1
    at Object.11.../utils (matrix.js:6379)
    at s (matrix.js:1)
    at matrix.js:1
    at Object.<anonymous> (matrix.js:1192)
    at Object.3../base-apis (matrix.js:4280)
```

But in the readme it says, that the only thing you have to do, is to include the .js file, and thats it.

> Download either the full or minified version from https://github.com/matrix-org/matrix-js-> sdk/releases/latest and add that as a <script> to your page. There will be a global variable matrixcs attached to window through which you can access the SDK.

It seems that you are excluding from bundling olm when building the release files.
`[...] browserify --exclude olm browser-index.js [...]`

If you don't want on bundling olm at all, thats fine, but it should be said in the readme on how to include it yourself or maybe provide an additional command that would bundle olm.js in the final js, something like `npm run buildFull`.

**Comment by richvdh** [comment]
hopefully fixed by https://github.com/matrix-org/matrix-js-sdk/pull/340

**Comment by electronicmax** [comment]
Hello. I'm still getting this error on the newest 0.7.6 release as of last night.... When will this be fixed?

**Comment by richvdh** [comment]
the olm load error is harmless; it just means that encryption is disabled. We can't include olm in the browserified bundles due to export regulations. If you want to use olm with matrix-js-sdk you'll have to supply it separately.
